### ISSUE TITLE
Mutations

### ISSUE THREAD

**Issue by janjaapbos** [aaivazis/nautilus#26]
Are mutations supported? If so, maybe the recipe example can be extended to show how?

**Comment by aaivazis** [comment]
Yes, mutations are supported. There isn't any kind of abstraction, just the normal graphene mutation objects. I'll try to add an example later today.

**Comment by aaivazis** [comment]
I just added an example mutation so you can see what that looks like. There are a few things to note about the general api which I don't like (hence why I didn't have a mutation in the example to begin with). Namely:

* the developer must remember to use the conventional names. This isn't too hard since nautilus already makes those availible, but i would prefer to have some sort of abstraction like `AddModelMutation(Recipe)` so that the user doesn't have to know. Of course, this would generalize to a `CRUDMutation` i'm just not sure on the semantics of the declaration. 
* The developer must remember to pass a dictionary to `dispatchAction` that has two keys: `type` and `payload` (ie `dispatchAction({'type': 'foo', 'payload': {'bar':'baz'})`) This is remnants from javascript and i would much prefer an api like `dispatch_action(type='foo', payload = {'bar':'baz'})`

**Comment by aaivazis** [comment]
I'm going to close this and move those two points to separate issues.
